name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 1622 sio.jbdelasalle.com >> ~/.ssh/known_hosts

    - name: Deploy to server with exclusions
      run: |
        sshpass -p ${{ secrets.PASSWORD_SIO_WIKI }} rsync -avz -e "ssh -p 1622" \
          --exclude-from='.deployignore' \
          ./ jfrachisse@sio.jbdelasalle.com:/home/SIO/jfrachisse/public_html/TP_Wiki

    - name: Set public read/execute on all files and folders except imgUpload
      run: |
        sshpass -p ${{ secrets.PASSWORD_SIO_WIKI }} ssh -p 1622 jfrachisse@sio.jbdelasalle.com \
          'chmod 755 /home/SIO/jfrachisse/public_html/TP_Wiki/'
          
    - name: Set write permissions on assets/imgUpload
      run: |
        sshpass -p ${{ secrets.PASSWORD_SIO_WIKI }} ssh -p 1622 jfrachisse@sio.jbdelasalle.com \
          'chmod 775 /home/SIO/jfrachisse/public_html/TP_Wiki/assets/imgUpload'

