name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no jfrachisse@sio.jbdelasalle.com 'echo "SSH connection works"'

    - name: Deploy to server
      run: |
        sshpass -p ${{ secrets.PASSWORD_SIO_WIKI }} scp -P 1622 -r . jfrachisse@sio.jbdelasalle.com:/home/SIO/jfrachisse/public_html

